#!/usr/bin/env python3
"""Choose the Unifont coverage that fits a byte budget (the 1 MB firmware app window).

Ranges are prioritised; each is added while it still fits, otherwise it is truncated to
the number of glyphs that do fit.  The result is written as a coverage file for
tools/gen_font.py.

Usage: tools/coverage-fit.py BUDGET_KB OUTPUT.txt
"""
import sys

HEX = "/usr/share/unifont/unifont.hex"
GLYPH_BYTES = 32
INDEX_BYTES_PER_GLYPH = 1.1   # page table + bitmap, measured
CORE_BYTES = 42000            # fm.cpp + the rest of the .rodata, measured

# (start, end, label) in priority order
BLOCKS = [
    (0x0020, 0x007E, "ASCII"),
    (0x4E00, 0x9FFF, "CJK Unified Ideographs (mandatory for Chinese)"),
    (0x00A0, 0x024F, "Latin-1 + Latin Extended-A/B"),
    (0x2000, 0x206F, "General Punctuation"),
    (0x2190, 0x21FF, "Arrows"),
    (0x2500, 0x257F, "Box Drawing"),
    (0x3000, 0x303F, "CJK Symbols and Punctuation"),
    (0xFF00, 0xFFEF, "Halfwidth and Fullwidth Forms"),
    (0x0370, 0x03FF, "Greek"),
    (0x0400, 0x052F, "Cyrillic"),
    (0x02B0, 0x02FF, "Spacing Modifier Letters"),
    (0x0250, 0x02AF, "IPA Extensions"),
    (0x2200, 0x22FF, "Mathematical Operators"),
    (0x2150, 0x218F, "Number Forms / Letterlike"),
    (0x2460, 0x24FF, "Enclosed Alphanumerics"),
    (0x25A0, 0x25FF, "Geometric Shapes"),
    (0x2580, 0x259F, "Block Elements"),
    (0x2600, 0x26FF, "Miscellaneous Symbols"),
    (0x2700, 0x27BF, "Dingbats"),
    (0x2300, 0x23FF, "Miscellaneous Technical"),
    (0x2000, 0x27FF, "remaining symbol blocks"),
    (0x3040, 0x30FF, "Hiragana + Katakana"),
    (0x2E80, 0x2FDF, "CJK Radicals + Kangxi"),
    (0x3100, 0x312F, "Bopomofo"),
    (0x31C0, 0x33FF, "CJK strokes / enclosed / compatibility"),
    (0xF900, 0xFAFF, "CJK Compatibility Ideographs"),
    (0xFE30, 0xFE4F, "CJK Compatibility Forms"),
    (0x3400, 0x4DBF, "CJK Extension A (traditional/rare)"),
]


def load_present():
    present = set()
    with open(HEX, encoding="ascii", errors="ignore") as f:
        for line in f:
            if ":" in line:
                try:
                    present.add(int(line.split(":", 1)[0], 16))
                except ValueError:
                    pass
    return present


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    budget = int(sys.argv[1]) * 1024
    present = load_present()
    used = CORE_BYTES
    chosen = []
    for start, end, label in BLOCKS:
        cps = [cp for cp in range(start, end + 1) if cp in present]
        if not cps:
            continue
        # how many of this range still fit?
        room = budget - used
        n = int(room / (GLYPH_BYTES + INDEX_BYTES_PER_GLYPH))
        if n <= 0:
            continue
        take = cps[:n]
        chosen.append((take[0], take[-1], label, len(take), len(cps)))
        used += int(len(take) * (GLYPH_BYTES + INDEX_BYTES_PER_GLYPH))
        if len(take) < len(cps):
            print("  truncated %-46s %d/%d glyphs" % (label, len(take), len(cps)))
        if label.startswith("CJK Unified"):
            print("  mandatory block: %d/%d glyphs, %.1f KB used so far"
                  % (len(take), len(cps), used / 1024.0))
    # merge overlapping ranges for the coverage file
    merged = []
    for a, b, *_ in sorted(chosen):
        if merged and a <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], b)
        else:
            merged.append([a, b])
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write("# generated by tools/coverage-fit.py -- budget %d KB\n" % (budget // 1024))
        for a, b in merged:
            f.write("%04X-%04X\n" % (a, b))
    total = sum(n for *_, n, _ in chosen)
    print("coverage: %d glyphs, estimated %.1f KB of app space" %
          (total, used / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
