#!/usr/bin/env python3
"""Generate src-style build/font-cjk/font_cjk.h: a compact 12x12 CJK bitmap table.

No firmware font API is involved: the glyphs are rasterized at build time from the Prime's
own system font (PrimeSans.ttf, extracted from ARMFIR.DAT) and compiled into the binary as
12 rows of 12 bits per glyph.  66 glyphs for the interface strings cost ~2 KB, so the whole
app stays far below the 1 MB app window.

Usage: tools/gen_cjk.py [--chars FILE] [--font TTF] [--outdir DIR] [--extra "汉字"]
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

CELL = 12          # glyph box in pixels (also used for ASCII: one font for everything)
BASELINE = 10      # baseline row inside the rendered strip
DIB_H = 20
PIXELSIZE = 12
THRESHOLD = 140


# Glyphs the system font renders too small/off-centre at 12 px; drawn by hand instead.
HAND_DRAWN = {
    "\u2190": [0x000, 0x000, 0x000, 0x100, 0x300, 0x7F0,
                0x7F0, 0x300, 0x100, 0x000, 0x000, 0x000],
    # the system font's underscore sits on the baseline and is clipped at 12 px
    "_": [0x000, 0x000, 0x000, 0x000, 0x000, 0x000,
          0x000, 0x000, 0x000, 0x000, 0xFF0, 0x000],
}


def rasterize(font, ch):
    from PIL import Image, ImageDraw
    img = Image.new("L", (CELL + 8, DIB_H), 255)
    d = ImageDraw.Draw(img)
    # ASCII is a proportional ~6 px wide at this size, CJK fills the box: shift narrow
    # glyphs right so they sit centred in the 12 px cell.
    xoff = 4 + (3 if ord(ch) < 0x2000 else 0)
    d.text((xoff, BASELINE - font.getmetrics()[0]), ch, font=font, fill=0)
    px = img.load()
    y0 = BASELINE - CELL + 1
    rows = []
    for ry in range(CELL):
        bits = 0
        for x in range(CELL):
            if px[4 + x, y0 + ry] < THRESHOLD:
                bits |= 1 << (CELL - 1 - x)  # MSB first: leftmost pixel is bit 11
        rows.append(bits)
    return rows


def trim(rows):
    first, last = 0, len(rows) - 1
    while first <= last and rows[first] == 0:
        first += 1
    while last >= first and rows[last] == 0:
        last -= 1
    if first > last:
        return 0, []
    return first, rows[first:last + 1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chars", default=os.path.join(HERE, "cjk_chars.txt"))
    ap.add_argument("--font", default="/root/prime/prime_fs_extracted/PrimeSans.ttf")
    ap.add_argument("--extra", default="")
    ap.add_argument("--outdir", default=os.path.join(ROOT, "build", "font-cjk"))
    args = ap.parse_args()

    try:
        from PIL import ImageFont
    except ImportError:
        print("Pillow is required (apt-get install python3-pil)", file=sys.stderr)
        return 1
    if not os.path.exists(args.font):
        print("system font %s not found" % args.font, file=sys.stderr)
        return 1

    # ASCII is rasterized from the very same system font as the CJK glyphs, so the whole
    # UI uses one typeface through one code path (the hand-made 5x7 table is gone).
    chars = set(chr(c) for c in range(0x20, 0x7F))
    if os.path.exists(args.chars):
        chars.update(c for c in open(args.chars, encoding="utf-8").read() if ord(c) > 0x7F)
    chars.update(c for c in args.extra if ord(c) > 0x7F)
    ordered = sorted(chars)
    if not ordered:
        print("no glyphs requested", file=sys.stderr)
        return 1

    font = ImageFont.truetype(args.font, PIXELSIZE)
    entries = []
    for ch in ordered:
        if ch in HAND_DRAWN:
            off, body = trim(HAND_DRAWN[ch])
        else:
            off, body = trim(rasterize(font, ch))
        entries.append((ord(ch), off, body))

    os.makedirs(args.outdir, exist_ok=True)
    out = os.path.join(args.outdir, "font_cjk.h")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_cjk.py -- DO NOT EDIT.\n")
        f.write("// 12x12 CJK/graphic glyphs rasterized from the Prime system font.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define FM_CJK_CELL 12\n")
        f.write("#define FM_CJK_COUNT %d\n\n" % len(entries))
        f.write("struct fm_cjk_glyph_t { uint16_t cp; uint8_t o; uint8_t n; uint16_t rows[12]; };\n\n")
        f.write("static const fm_cjk_glyph_t fm_cjk_table[FM_CJK_COUNT] = {\n")
        for cp, off, body in entries:
            rows = ", ".join("0x%03x" % r for r in body)
            f.write("  { 0x%04X, %2d, %2d, { %s } },\n" % (cp, off, len(body), rows))
        f.write("};\n")
    print("wrote %s: %d glyphs, %d bytes of ink data" %
          (out, len(entries), 2 * sum(len(b) for _, _, b in entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
