#!/usr/bin/env python3
"""Generate the font tables for fm.elf / fmen.elf from GNU Unifont.

Two tables are produced:

  build/font-uf/font_uf.h   UI table: ASCII (8x16 face) + the character set used by the
                            interface strings, scanned from src/ and lang/ so adding text
                            never needs a hand maintained list.
  build/font-gb/font_gb.h   GB2312 support for the Chinese build: a 94*94 byte-pair ->
                            Unicode map plus a 16x16 glyph table for every character.
                            With --no-han only the UI table is emitted (English build).

Usage:
  tools/gen_gb2312.py                       # Chinese build tables
  tools/gen_gb2312.py --no-han --outdir build/font-en
"""
import argparse
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Mainland glyph forms.  unifont_jp.hex has the same coverage but draws some characters with
# Japanese/traditional shapes (径 as 徑), which looks wrong in a Chinese interface.
CJK_HEX = "/usr/share/unifont/unifont.hex"
CJK_FALLBACK = "/usr/share/unifont/unifont_jp.hex"
ASCII_HEX = "/usr/share/unifont/unifont.hex"

# Glyphs the interface needs that are not covered by the scans (arrow, box bar).
EXTRA_CPS = (0x2190, 0x2500)


def read_hex(path, wanted):
    """{codepoint: [16 row bitmaps]} for the wanted codepoints. 8 px glyphs are stored with
    the row byte in the high half, which is how the renderer detects the width."""
    out = {}
    if not os.path.exists(path):
        return out
    with open(path, encoding="ascii", errors="ignore") as f:
        for line in f:
            if ":" not in line:
                continue
            left, hexdata = line.split(":", 1)
            try:
                cp = int(left, 16)
            except ValueError:
                continue
            if cp not in wanted or cp in out:
                continue
            try:
                raw = bytes.fromhex(hexdata.strip())
            except ValueError:
                continue
            if len(raw) == 16:
                out[cp] = [b << 8 for b in raw]
            elif len(raw) == 32:
                out[cp] = [(raw[i * 2] << 8) | raw[i * 2 + 1] for i in range(16)]
    return out


def gb2312_pairs():
    out = []
    for hi in range(0xA1, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                ch = bytes([hi, lo]).decode("gb2312")
            except Exception:
                continue
            out.append(((hi - 0xA1) * 94 + (lo - 0xA1), ord(ch)))
    return out


def upscale(rows, factor):
    if factor <= 1:
        return rows
    out = []
    for r in rows:
        big = 0
        for c in range(16):
            if (r >> (15 - c)) & 1:
                for k in range(factor):
                    x = c * factor + k
                    if x < 16:
                        big |= 1 << (15 - x)
        for _ in range(factor):
            out.append(big)
    return out


def trim(rows):
    first, last = 0, len(rows) - 1
    while first <= last and rows[first] == 0:
        first += 1
    while last >= first and rows[last] == 0:
        last -= 1
    if first > last:
        return 0, []
    return first, rows[first:last + 1]


def scan_chars(dirs):
    cps = set(EXTRA_CPS)
    for d in dirs:
        for pattern in ("*.c", "*.cpp", "*.h", "*.inc"):
            for path in glob.glob(os.path.join(d, pattern)):
                with open(path, encoding="utf-8", errors="ignore") as f:
                    for ch in f.read():
                        if ord(ch) > 0x7F:
                            cps.add(ord(ch))
    cps.discard(0xFFFD)
    return cps


def write_ui(path, entries, cell_h):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_gb2312.py -- DO NOT EDIT.\n")
        f.write("// ASCII (8x16 face) plus the glyphs used by the interface strings.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define UF_CELL_H %d\n#define UF_COUNT %d\n\n" % (cell_h, len(entries)))
        f.write("struct uf_glyph_t { uint16_t cp; int16_t off; uint8_t n; uint8_t w; uint16_t rows[16]; };\n\n")
        f.write("static const uf_glyph_t uf_table[UF_COUNT] = {\n")
        for cp, off, n, w, body in entries:
            f.write("  { 0x%04X, %2d, %2d, %2d, { %s } },\n" %
                    (cp, off, n, w, ", ".join("0x%04x" % r for r in body)))
        f.write("};\n")


def write_gb(path, table, entries):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_gb2312.py from GNU Unifont -- DO NOT EDIT.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("/* GB2312 byte pair -> Unicode; 0xFFFD marks an unused pair. */\n")
        f.write("#define GB_MAP_SIZE %d\n" % len(table))
        f.write("static const uint16_t gb2312_map[GB_MAP_SIZE] = {\n")
        for i in range(0, len(table), 16):
            f.write("  " + ",".join("0x%04x" % v for v in table[i:i + 16]) + ",\n")
        f.write("};\n\n")
        f.write("/* 16x16 glyph for every GB2312 character (sorted by codepoint). */\n")
        f.write("#define GB_HAN_COUNT %d\n" % len(entries))
        f.write("struct gb_glyph_t { uint16_t cp; int16_t off; uint8_t n; uint16_t rows[16]; };\n")
        f.write("static const gb_glyph_t gb2312_han[GB_HAN_COUNT] = {\n")
        for cp, off, n, body in entries:
            f.write("  { 0x%04X, %2d, %2d, { %s } },\n" %
                    (cp, off, n, ", ".join("0x%04x" % r for r in body)))
        f.write("};\n")


def write_gb_empty(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_gb2312.py --no-han -- DO NOT EDIT.\n")
        f.write("// The English build carries no GB2312 table.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define GB_MAP_SIZE 1\n")
        f.write("static const uint16_t gb2312_map[GB_MAP_SIZE] = { 0xFFFD };\n")
        f.write("#define GB_HAN_COUNT 0\n")
        f.write("struct gb_glyph_t { uint16_t cp; int16_t off; uint8_t n; uint16_t rows[16]; };\n")
        f.write("static const gb_glyph_t gb2312_han[1] = { { 0, 0, 0, { 0 } } };\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hex", default=CJK_HEX)
    ap.add_argument("--fallback-hex", default=CJK_FALLBACK)
    ap.add_argument("--ascii-hex", default=ASCII_HEX)
    ap.add_argument("--scan", nargs="*", default=[os.path.join(ROOT, "src"), os.path.join(ROOT, "lang")])
    ap.add_argument("--scale", type=int, default=1, help="integer glyph upscale (1 = 16 px cell)")
    ap.add_argument("--no-han", action="store_true", help="UI table only (English build)")
    ap.add_argument("--outdir", default=os.path.join(ROOT, "build", "font-gb"))
    ap.add_argument("--ui-outdir", default=os.path.join(ROOT, "build", "font-uf"))
    args = ap.parse_args()

    scale = max(1, args.scale)
    ui_cps = scan_chars(args.scan)
    ascii_cps = set(range(0x20, 0x7F))

    glyphs = read_hex(args.ascii_hex, ascii_cps | ui_cps)
    for cp, rows in read_hex(args.hex, ui_cps).items():
        if cp not in glyphs or not any(glyphs[cp]):
            glyphs[cp] = rows
    for cp, rows in read_hex(args.fallback_hex, ui_cps).items():
        if cp not in glyphs or not any(glyphs[cp]):
            glyphs[cp] = rows

    ui_entries = []
    for cp in sorted(set(glyphs) & (ascii_cps | ui_cps)):
        rows = glyphs[cp]
        if not any(rows):
            continue
        w = 8 if all(not (r & 0x00FF) for r in rows) else 16
        if scale > 1:
            rows = upscale(rows, scale)
        off, body = trim(rows)
        ui_entries.append((cp, off, len(body), w * scale, body))
    write_ui(os.path.join(args.ui_outdir, "font_uf.h"), ui_entries, 16 * scale)
    missing = sorted(ui_cps - set(glyphs))
    if missing:
        print("warning: %d UI characters have no glyph: %s" %
              (len(missing), " ".join(chr(c) for c in missing[:10])), file=sys.stderr)
    print("UI table: %d glyphs -> %s" % (len(ui_entries), args.ui_outdir))

    if args.no_han:
        write_gb_empty(os.path.join(args.outdir, "font_gb.h"))
        print("GB table: omitted (--no-han)")
        return 0

    pairs = gb2312_pairs()
    han_cps = sorted(set(cp for _, cp in pairs))
    han_src = read_hex(args.hex, set(han_cps))
    for cp, rows in read_hex(args.fallback_hex, set(han_cps)).items():
        if cp not in han_src or not any(han_src[cp]):
            han_src[cp] = rows
    blank = set(cp for cp, rows in han_src.items() if not any(rows))
    table = [0xFFFD] * (94 * 94)
    for idx, cp in pairs:
        table[idx] = cp if (cp in han_src and cp not in blank) else 0xFFFD
    han_entries = []
    for cp in han_cps:
        if cp not in han_src or cp in blank:
            continue
        rows = upscale(han_src[cp], scale) if scale > 1 else han_src[cp]
        off, body = trim(rows)
        han_entries.append((cp, off, len(body), body))
    write_gb(os.path.join(args.outdir, "font_gb.h"), table, han_entries)
    if blank:
        print("note: %d character(s) marked unused (blank glyph): %s" %
              (len(blank), ", ".join("U+%04X" % c for c in sorted(blank))), file=sys.stderr)
    print("GB table: %d pairs, %d glyphs -> %s" % (len(pairs), len(han_entries), args.outdir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
