#!/usr/bin/env python3
"""Generate build/font-uf/font_uf.h: a compact GNU Unifont subset as C tables.

Only the glyphs the file manager can actually show are embedded, so the "big blob" problem
that made Unifont unusable before cannot come back:

    ASCII  U+0020..U+007E   8x16 bitmaps, 16 bytes each   (Unifont .hex stores 16 hex digits)
    other  tools/cjk_chars.txt + extras, 16x16 bitmaps, 32 bytes each

Lookup is a binary search over a sorted {codepoint, offset, width} index, so the tables can
be plain `static const` data in the image -- the same kind of small in-image table that the
bring-up probe proved stable on the device.

Usage: tools/gen_ufont.py [--ascii-hex F] [--cjk-hex F] [--chars F] [--outdir D] [--extra S]
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

ASC_HEX = "/usr/share/unifont/unifont.hex"
CJK_HEX = "/usr/share/unifont/unifont_sample.hex"
CJK_SYS = "/usr/share/unifont/unifont.hex"


def read_hex(path, wanted):
    """Return {cp: [rows]} for the requested codepoints, rows as (byte << 8 | 0)."""
    out = {}
    if not os.path.exists(path):
        return out
    with open(path, encoding="ascii", errors="ignore") as f:
        for line in f:
            if ":" not in line:
                continue
            left, hexdata = line.split(":", 1)
            try:
                cp = int(left, 16)
            except ValueError:
                continue
            if cp not in wanted or cp in out:
                continue
            data = hexdata.strip()
            try:
                raw = bytes.fromhex(data)
            except ValueError:
                continue
            if len(raw) == 16:  # 8 px wide: one byte per row, left aligned
                out[cp] = [b << 8 for b in raw]
            elif len(raw) == 32:  # 16 px wide: two bytes per row, big endian
                out[cp] = [((raw[i * 2] << 8) | raw[i * 2 + 1]) << 0 for i in range(16)]
            else:
                continue
    return out


def trim(rows):
    first, last = 0, len(rows) - 1
    while first <= last and rows[first] == 0:
        first += 1
    while last >= first and rows[last] == 0:
        last -= 1
    if first > last:
        return 0, []
    return first, rows[first:last + 1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ascii-hex", default=ASC_HEX)
    ap.add_argument("--cjk-hex", default=CJK_HEX)
    ap.add_argument("--chars", default=os.path.join(HERE, "cjk_chars.txt"))
    ap.add_argument("--extra", default="")
    ap.add_argument("--outdir", default=os.path.join(ROOT, "build", "font-uf"))
    args = ap.parse_args()

    wanted_ascii = set(range(0x20, 0x7F))
    wanted_other = set()
    if os.path.exists(args.chars):
        wanted_other.update(ord(c) for c in open(args.chars, encoding="utf-8").read() if ord(c) > 0x7F)
    wanted_other.update(ord(c) for c in args.extra if ord(c) > 0x7F)
    wanted_other.discard(0)
    wanted_other.update((0x2190, 0xFF0C, 0x2500))  # arrow, fullwidth comma, box bar

    glyphs = read_hex(args.ascii_hex, wanted_ascii)
    # CJK: unifont_sample.hex first (glyphs drawn on the 16x16 grid), then unifont.hex
    for cp, rows in read_hex(args.cjk_hex, wanted_other).items():
        glyphs.setdefault(cp, rows)
    for cp, rows in read_hex(CJK_SYS, wanted_other).items():
        glyphs.setdefault(cp, rows)

    missing = sorted((wanted_ascii | wanted_other) - set(glyphs))
    if missing:
        print("warning: %d codepoints not found, first: %s" %
              (len(missing), ", ".join("U+%04X" % c for c in missing[:8])), file=sys.stderr)

    os.makedirs(args.outdir, exist_ok=True)
    out = os.path.join(args.outdir, "font_uf.h")
    entries = []
    for cp in sorted(glyphs):
        rows = glyphs[cp]
        width = 8 if all(not (r & 0xFF) for r in rows) else 16
        off, body = trim(rows)
        entries.append((cp, off, len(body), width, body))

    with open(out, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/gen_ufont.py from GNU Unifont -- DO NOT EDIT.\n")
        f.write("// Unifont subset: ASCII 8x16 + the interface's CJK/graphic glyphs 16x16.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("#define UF_CELL_H 16\n")
        f.write("#define UF_COUNT %d\n\n" % len(entries))
        f.write("struct uf_glyph_t { uint16_t cp; int16_t off; uint8_t n; uint8_t w; uint16_t rows[16]; };\n\n")
        f.write("static const uf_glyph_t uf_table[UF_COUNT] = {\n")
        for cp, off, n, w, body in entries:
            rows = ", ".join("0x%04x" % r for r in body)
            f.write("  { 0x%04X, %2d, %2d, %2d, { %s } },\n" % (cp, off, n, w, rows))
        f.write("};\n\n")
        f.write("/* First codepoint that is not 8 px wide (ASCII ends here). */\n")
        wide = [cp for cp, _, _, w, _ in entries if w == 16]
        f.write("#define UF_FIRST_WIDE 0x%04X\n" % (wide[0] if wide else 0xFFFF))
    print("wrote %s: %d glyphs (%d ascii, %d wide), %d bytes of ink" %
          (out, len(entries), len(wanted_ascii & set(glyphs)),
           sum(1 for _, _, _, w, _ in entries if w == 16),
           2 * sum(n for _, _, n, _, _ in entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
